version: '3.8'
services:
  api:
    container_name: server
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    environment:
      - PORT=8080
      - NODE_ENV=development
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - REGION=ap-southeast-1
    networks:
      - app-network
    develop:
      watch:
        - path: ./server/package.json
          action: rebuild
        - path: ./server/package-lock.json
          action: rebuild
        - path: ./server
          target: /app
          action: sync

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network
    develop:
      watch:
        - path: ./clien/package.json
          action: rebuild
        - path: ./client/package-lock.json
          action: rebuild
        - path: ./client
          target: /app
          action: sync

  dynamodb-local:
    container_name: db
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

        


